# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
        snapshot:
          type: boolean
          description: Set the snapshot qualifier
        uptick_target:
          type: choice
          description: Transform version
          options:
            - Major
            - Minor
            - Micro
            - None

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: Checkout
      uses: actions/checkout@v3

    # Make changes to pull request here
    - name: Run command in the shell
      run: |
           echo ${{ github.event.inputs.uptick_target }} >> README.md
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
